{
    imports = [
      ./btop.nix
      ./equibop.nix
      ./flatpak.nix
      ./foot.nix
      ./ghostty.nix
      ./nh.nix 
      ./spotify-player.nix
      ./spicetify.nix
      ./starship.nix  
      ./zathura.nix
      ./zoxide.nix
      ./shell.nix
      ./hyprpanel.nix
      ./niri.nix 
      ./wezterm
      ./scripts 
      ./terminal
      ./editors
      ./matugen
    ];
}
