#!/bin/bash

# Obtener el estado de muteo del micrófono en PulseAudio
MUTE_STATE=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

# Comprobar el estado y devolver el output correspondiente
if [ "$MUTE_STATE" = "yes" ]; then
    echo "MUTE"
else
    echo "MICON"
fi
