#!/bin/bash

# Obtener el estado de muteo de PulseAudio
MUTE_STATE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

# Comprobar el estado y devolver el output correspondiente
if [ "$MUTE_STATE" = "yes" ]; then
    echo "MUTE"
else
    echo "SOUND"
fi
