{ pkgs, inputs, config, lib, ...}:
 let 
  set-volume = "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@";
  brillo = "${pkgs.brillo}/bin/brillo" "-q" "-u" "300000";
  playerctl = "${pkgs.playerctl}/bin/playerctl";
  control-center = "env" "XDG_CURRENT_DESKTOP=gnome" "gnome-control-center";
  walkern = "${inputs.walker.packages.${pkgs.system}.default}/bin/walker";
  wallPicker = "walker" "-m" "wallpaper";
  walker-clip = "niri-clip";
  wallpaperScript = pkgs.writeScriptBin "niri-wallpaper" (builtins.readFile ./wallpaperAutoChange.sh);
in 
{
  binds = {
    XF86AudioMute = { spawn = [ "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle" ]; };
    XF86AudioMicMute = { spawn = [ "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle" ]; };
    XF86AudioPlay = { spawn = [ "playerctl" "play-pause" ]; };
    XF86AudioStop = { spawn = [ "playerctl" "pause" ]; };
    XF86AudioPrev = { spawn = [ "playerctl" "previous" ]; };
    XF86AudioNext = { spawn = [ "playerctl" "next" ]; };
    XF86AudioRaiseVolume = { spawn = [ "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+" ]; };
    XF86AudioLowerVolume = { spawn = [ "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%-" ]; };
    XF86MonBrightnessUp = { spawn = [ "brightness" "--inc" ]; };
    XF86MonBrightnessDown = { spawn = [ "brightness" "--dec" ]; };
    Print = { screenshot-screen = true; };
    "Mod+Shift+Alt+S" = { screenshot-window = true; };
    "Mod+Shift+S" = { screenshot = true; };
    "Mod+D" = { spawn = [ "walker" ]; };
    "Mod+R" = { spawn = [ "fuzzel" ]; };
    "Mod+N" = { spawn = [ "toggle-waybar" ]; };
    "Mod+Return" = { spawn = [ "wezterm" ]; };
    "Mod+X" = { spawn = [ "walker" "-m" "power" ]; };
    "Alt+Tab" = { spawn = [ "walker" "-m" "windows" ]; };
    "Mod+Shift+X" = { spawn = [ "ani-cli" "--rofi" ]; };
    "Alt+Space" = { spawn = [ "${pkgs.anyrun}/bin/anyrun" ]; };
    "Mod+Shift+Return" = { spawn = [ "ghostty" ]; };
    "Ctrl+Alt+L" = { spawn = [ "hyprlock" ]; };
    "Mod+T" = { spawn = [ "thunar" ]; };
    "Mod+U" = { spawn = [ "env" "XDG_CURRENT_DESKTOP=gnome" "gnome-control-center" ]; };
    "Mod+E" = { spawn = [ "walker" "-m" "wallpaper" ]; };
    "Mod+Backspace" = { spawn = [ "wlogout-new" ]; };
    "Mod+B" = { spawn = [ "eww-bar" ]; };
    "Mod+Q" = { close-window = true; };
    "Mod+S" = { switch-preset-column-width = true; };
    "Mod+F" = { maximize-column = true; };
    "Mod+M" = { spawn = [ "niri-edit" ]; };
    "Mod+Shift+F" = { expand-column-to-available-width = true; };
    "Mod+Space" = { toggle-window-floating = true; };
    "Mod+W" = { toggle-column-tabbed-display = true; };
    "Mod+V" = { spawn = [ "walker" "-m" "clipboard" ]; };
    "Mod+Comma" = { consume-window-into-column = true; };
    "Mod+Period" = { expel-window-from-column = true; };
    "Mod+C" = { center-window = true; };
    "Mod+Tab" = { switch-focus-between-floating-and-tiling = true; };
    "Mod+Minus" = { set-column-width = "-10%"; };
    "Mod+Equal" = { set-column-width = "+10%"; };
    "Mod+Shift+Minus" = { set-window-height = "-10%"; };
    "Mod+Shift+Equal" = { set-window-height = "+10%"; };
    "Mod+H" = { focus-column-left = true; };
    "Mod+L" = { focus-column-right = true; };
    "Mod+J" = { focus-window-or-workspace-down = true; };
    "Mod+K" = { focus-window-or-workspace-up = true; };
    "Mod+Left" = { focus-column-left = true; };
    "Mod+Right" = { focus-column-right = true; };
    "Mod+Down" = { focus-workspace-down = true; };
    "Mod+Up" = { focus-workspace-up = true; };
    "Mod+Shift+H" = { move-column-left = true; };
    "Mod+Shift+L" = { move-column-right = true; };
    "Mod+Shift+K" = { move-column-to-workspace-up = true; };
    "Mod+Shift+J" = { move-column-to-workspace-down = true; };
    "Mod+Shift+Ctrl+J" = { move-column-to-monitor-down = true; };
    "Mod+Shift+Ctrl+K" = { move-column-to-monitor-up = true; };
    "Mod+1" = { focus-workspace = 1; };
    "Mod+2" = { focus-workspace = 2; };
    "Mod+3" = { focus-workspace = 3; };
  };
}
