alias gcl "git clone"
alias sv "sudo -E nvim"
alias fm yazi
alias ranger yazi
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
alias cn "cd ~/NixOS-Hyprland"
alias ls "eza --long --header --icons --git --group-directories-first "
#alias ls "lsd"
alias l "ls -a"
alias lt "lsd --tree"
alias gadd "git add ."
alias gcommit "git commit -m"
alias gpush "git push -u origin main"
alias ... "cd ../.."
alias .... "cd ../../.."
alias fuck "nh os switch"
alias fucku "nh os switch --update"
alias rollfuck "sudo nixos-rebuild switch --rollback --flake .#shizuru"
alias fuckgc "nh clean all"
alias fuckdit "codium ~/NixOS-Hyprland"
alias x "exit"
alias e "clear"
alias ff "fastfetch"
alias nf "nitch"
alias mf "microfetch"
alias cl "zellij"
alias fucknix "sudo nixos-rebuild switch --flake .#shizuru"
alias cd "z"
alias listgen "sudo nix-env -p /nix/var/nix/profiles/system --list-generations";
