#!/bin/bash

wall_animation=none

# Leer el tema actual
read -r current_rice <"$HOME/.config/hypr/eww/themes/.theme"

# Definir el directorio de fondos de pantalla
wall_dir="$HOME/.config/hypr/eww/themes/$current_rice/walls"

# Seleccionar un fondo de pantalla aleatorio
wallpaper=$(find "$wall_dir" -type f | shuf -n 1)

# Aplicar el fondo de pantalla con swww y animacion
swww img "$wallpaper" --transition-type $wall_animation

$HOME/.config/hypr/eww/scripts/WallWay $wallpaper
