#!/bin/bash

# Nombre del monitor fijo
monitor="DP-1"

# Ruta del archivo de salida
archivo="$HOME/Videos/$(date '+%Y-%m-%d_%H-%M-%S').mp4"

# Ejecutar wf-recorder en ese monitor
wf-recorder -o "$monitor" -f "$archivo" -r 30


