#!/bin/bash

# Ruta y nombre de archivo
timestamp=$(date +%Y-%m-%d-%H%M%S)
dir="$HOME/Pictures/ScreenShots"
filename="$dir/Shot-${timestamp}.png"

# Crear directorio si no existe
[ -d "$dir" ] || mkdir -p "$dir"

# Notificación (reemplaza dunstify)
show_notification() {
    if [[ -e "$filename" ]]; then
        notify-send -i "$filename" "Screenshot" "Screenshot saved and copied to clipboard"
    else
        notify-send -i "dialog-error" "Screenshot" "Screenshot Canceled"
    fi
}

# Copiar captura al portapapeles
copy_screenshot() {
    wl-copy < "$filename"
}

# Capturar pantalla
take_screenshot() {
    local mode="$1"

    case "$mode" in
        "full")
            grim "$filename"
            ;;
        "select")
            grim -g "$(slurp)" "$filename"
            ;;
    esac

    if [[ $? -eq 0 ]]; then
        copy_screenshot
        show_notification
    fi
}

# Cuenta regresiva
countdown() {
    for sec in $(seq "$1" -1 1); do
        notify-send -t 1000 "Taking shot in: $sec" -i $HOME/.config/hypr/eww/images/ss.svg
        sleep 1
    done
}

# Comandos para usar en Eww
case "$1" in
    "full")
        sleep 1 && take_screenshot "full" ;;
    "select")
        take_screenshot "select" ;;
    "in3")
        countdown 3 && sleep 1 && take_screenshot "full" ;;
    *)
        echo "Usage: $0 {full|select|in3}" ;;
esac

