#!/usr/bin/env bash
#  ██╗    ██╗ █████╗ ██╗     ██╗
#  ██║    ██║██╔══██╗██║     ██║
#  ██║ █╗ ██║███████║██║     ██║
#  ██║███╗██║██╔══██║██║     ██║
#  ╚███╔███╔╝██║  ██║███████╗███████╗
#   ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝

# Read theme flag
read -r current_rice <"$HOME/.config/hypr/eww/themes/.theme"
wall_dir="$HOME/.config/hypr/eww/themes/$current_rice/walls"

# Open Waypaper in theme folder
pgrep waypaper && pkill waypaper || waypaper --folder $wall_dir &

